#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive out of it
mysqldump -u root -p"$1" --all-databases > backup.sql
currentDate=$(date +"%d-%m-%Y")
tar -cvzf "$currentDate".tar.gz backup.sql
