#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd
# using the while loop + IFS.
input="/etc/passwd"
IFS=':'
while read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_SHELL
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$USERNAME" "$GROUP_ID" "$HOME_DIRECTORY" "$COMMAND_SHELL" "$USER_ID" "$PASSWORD" "$USER_ID_INFO"
done < "$input"
