#!/usr/bin/env bash
# a Bash script that fix container so that Nginx is running as the nginx user
pkill apache 2
chmod -R 777 /etc/nginx/
sed -i "1 i\user nginx;" /etc/nginx/nginx.conf
sed -i "s\listen 80 default_server;\listen 8080 default_server;" /etc/nginx/sites-available/default
sed -i "s\listen [::]:80 default_server ipv6only=on;\listen [::]:8080 default_server ipv6only=on;" /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
