#!/usr/bin/env bash
# a Bash script that fix container so that Nginx is running as the nginx user
pkill apache 2
chmod -R 777 /etc/nginx/
sed -i "1 i\user nginx;" /etc/nginx/nginx.conf
sed -i "s\80\8080" /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
